version: "{build}"

os: Visual Studio 2015

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

# scripts that need to be run prior to repo cloning...
init:
  - cmd: cmake --version

install:
  # install tinyxml2
  - cmd: git clone https://github.com/leethomason/tinyxml2.git
  - cmd: cd tinyxml2
  - cmd: cmake . && make install

branches:
  - except:
    - gh-pages
